apiVersion: v1
kind: Service
metadata:
  name: weerservice
  annotations:
    metallb.io/address-pool: ip-pool
    metallb.universe.tf/loadBalancerIPs: 10.10.90.33
spec:
  selector:
    app: weerservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
