kube-prometheus-stack:
  # 1. Alertmanager
  alertmanager:
    enabled: true
    config:
      global:
        resolve_timeout: 5m
      route:
        group_by: ['job']
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 12h
        receiver: 'null'
        routes:
          - match:
              alertname: Watchdog
            receiver: 'null'
      receivers:
        - name: 'null'

  # 2. Grafana
  grafana:
    enabled: true
    adminPassword: "prom-operator"
    service:
      type: LoadBalancer
    # Fix "Database Locked" error
    grafana.ini:
      database:
        wal: true
    # Fix "Permission Denied" error
    securityContext:
      runAsNonRoot: false
      runAsUser: 0
      fsGroup: 0

  # 3. Node Exporter
  nodeExporter:
    enabled: false

  # 4. Prometheus
  prometheus:
    prometheusSpec:
      # Fix 1: Permissions (Keep this)
      securityContext:
        runAsUser: 0
        runAsNonRoot: false
        fsGroup: 0
      
      # Fix 2: THE NEW FIX (Increase CPU for the reloader) 🚀
      configReloaderResources:
        limits:
          cpu: 200m
          memory: 50Mi
        requests:
          cpu: 50m
          memory: 50Mi

      # Fix 3: Tell Prometheus to read the Alpine Host!
      additionalScrapeConfigs:
        - job_name: 'alpine-vm-host'
          static_configs:
            - targets: ['10.10.90.151:9100']
