apiVersion: apps/v1
kind: Deployment
metadata:
  name: weerservice
spec:
  replicas: 3 # Draai 3 kopieën voor load-balancing en uptime
  selector:
    matchLabels:
      app: weerservice
  template:
    metadata:
      labels:
        app: weerservice
    spec:
      containers:
        - name: weerservice
          image: n64docker/testmet:latest
          ports:
            - containerPort: 80
          # Belangrijk voor uptime:
          readinessProbe:
            httpGet:
              path: /
              port: 80
