apiVersion: v1
kind: Service
metadata:
  name: weer-app
  annotations:
    metallb.io/address-pool: ip-pool
spec:
  selector:
    app: weer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer